<?php

/**
 * @file
 * Overrides core contact form functionality
 */

use Drupal\contact\MessageForm;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\contact\ContactFormInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\contact\Entity\ContactForm;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\HtmlCommand;
use Drupal\Core\Ajax\ReplaceCommand;
use Drupal\node\Entity\Node;
use Drupal\Core\Render\Element\StatusMessages;

/**
 * Contact ajax form prefix
 */
const CONTACT_AJAX_PREFIX = 'contact_ajax_';

/**
 * Reload the form after submit
 */
const CONTACT_AJAX_LOAD_FORM = 1;

/**
 * Load the content from another node
 */
const CONTACT_AJAX_LOAD_FROM_URI = 2;

/**
 * Load the content from the message
 */
const CONTACT_AJAX_LOAD_FROM_MESSAGE = 3;

/**
 * Implements hook_form_FORM_ID_alter() for contact_form_form().
 */
function contact_ajax_form_contact_form_form_alter(&$form, FormStateInterface $form_state) {
  /** @var \Drupal\contact\ContactFormInterface $contact_form */
  $contact_form = $form_state->getFormObject()->getEntity();

  $form['contact_ajax'] = array(
    '#type' => 'fieldset',
    '#title' => t('Contact ajax'),
  );

  $form['contact_ajax']['contact_ajax_enabled'] = [
    '#type' => 'checkbox',
    '#title' => t('Ajax Form'),
    '#description' => t('Send this form using ajax.'),
    '#default_value' => $contact_form->getThirdPartySetting('contact_ajax', 'enabled', FALSE),
  ];

  //
  // This settings is TRUE for default, the contact_form will be always
  // hide after the submission.
  //
  // $form['contact_ajax']['contact_ajax_hide_form'] = [
  //   '#type' => 'checkbox',
  //   '#title' => t('Hide form on success'),
  //   '#description' => t('When the ajax submission return without error hide the contact form.'),
  //   '#default_value' => $contact_form->getThirdPartySetting('contact_ajax', 'hide_form', FALSE),
  //   '#states' => array(
  //     'visible' => array(
  //       ':input[name="contact_ajax_enabled"]' => array('checked' => TRUE),
  //     ),
  //   ),
  // ];

  $form['contact_ajax']['contact_ajax_confirmation_type'] = [
    '#type' => 'select',
    '#title' => t('On submit load'),
    '#description' => t('Select which content have to be loaded after submit.'),
    '#options' => array(
        CONTACT_AJAX_LOAD_FORM => t('Default message'),
        CONTACT_AJAX_LOAD_FROM_URI => t('Node content'),
        CONTACT_AJAX_LOAD_FROM_MESSAGE => t('Custom message'),
      ),
    '#default_value' => $contact_form->getThirdPartySetting('contact_ajax', 'confirmation_type', FALSE),
    '#states' => array(
      'visible' => array(
        ':input[name="contact_ajax_enabled"]' => array('checked' => TRUE),
      ),
    ),
  ];

  // default entity_autocomplete get a node object as default value
  $node_id = $contact_form->getThirdPartySetting('contact_ajax', 'load_from_uri', FALSE);
  $node = $node_id ? Node::load($node_id) : FALSE;
  $form['contact_ajax']['contact_ajax_load_from_uri'] = [
    '#type' => 'entity_autocomplete',
    '#target_type' => 'node',
    '#default_value' => $node,
    '#title' => t('Node to load'),
    '#description' => t('This node will load its content after the form Submit.'),
    '#states' => array(
      'visible' => array(
        ':input[name="contact_ajax_enabled"]' => array('checked' => TRUE),
        ':input[name="contact_ajax_confirmation_type"]' => array('value' => CONTACT_AJAX_LOAD_FROM_URI),
      ),
    ),
  ];

  $confirmation_message = $contact_form->getThirdPartySetting('contact_ajax', 'load_from_message', FALSE);
  $confirmation_message_value = $confirmation_message ? $confirmation_message['value'] : '';
  $form['contact_ajax']['contact_ajax_load_from_message'] = [
    '#type' => 'text_format',
    '#title' => t('Message to load'),
    '#description' => t('This message will load after form submit.'),
    '#default_value' => $confirmation_message_value,
    '#states' => array(
      'visible' => array(
        ':input[name="contact_ajax_enabled"]' => array('checked' => TRUE),
        ':input[name="contact_ajax_confirmation_type"]' => array('value' => CONTACT_AJAX_LOAD_FROM_MESSAGE),
      ),
    ),
  ];

  $form['contact_ajax']['advanced'] = array(
    '#type' => 'details',
    '#title' => t('ADVANCED SETTINGS'),
    '#open' => FALSE,
    //'#collapsed' => TRUE,
    '#states' => array(
      'visible' => array(
        ':input[name="contact_ajax_enabled"]' => array('checked' => TRUE),
      ),
    ),
  );

  $form['contact_ajax']['advanced']['contact_ajax_prefix_id'] = [
    '#type' => 'textfield',
    '#title' => t('Prefix id'),
    '#description' => t('When contact ajax is enabled, a wrapper is created around the form, with this settings you can choose a custom ID from the HTML wrapper element. Leave empty if you don\'t need it'),
    '#default_value' => $contact_form->getThirdPartySetting('contact_ajax', 'prefix_id', FALSE),
    '#states' => array(
      'visible' => array(
        ':input[name="contact_ajax_enabled"]' => array('checked' => TRUE),
      ),
    ),
  ];

  $form['contact_ajax']['advanced']['contact_ajax_render_selector'] = [
    '#type' => 'textfield',
    '#title' => t('Render into this HTML element class/id'),
    '#description' => t('If you need to load the response into an element different from Prefix_id you can write here the class id. i.e : .render-here , #render-here.'),
    '#default_value' => $contact_form->getThirdPartySetting('contact_ajax', 'render_selector', FALSE),
    '#states' => array(
      'visible' => array(
        ':input[name="contact_ajax_enabled"]' => array('checked' => TRUE),
      ),
    ),
  ];

  $form['#entity_builders'][] = 'contact_ajax_contact_form_form_builder';
}

/**
 * Entity builder for the contact form edit form with third party options.
 *
 * @see contact_ajax_test_form_contact_form_edit_form_alter()
 */
function contact_ajax_contact_form_form_builder($entity_type, ContactFormInterface $contact_form, &$form, FormStateInterface $form_state) {
  $contact_form->setThirdPartySetting('contact_ajax', 'enabled', $form_state->getValue('contact_ajax_enabled'));
  $contact_form->setThirdPartySetting('contact_ajax', 'prefix_id', $form_state->getValue('contact_ajax_prefix_id'));
  $contact_form->setThirdPartySetting('contact_ajax', 'render_selector', $form_state->getValue('contact_ajax_render_selector'));

  // get the confirmation type
  $confirmation_type = $form_state->getValue('contact_ajax_confirmation_type');
  $contact_form->setThirdPartySetting('contact_ajax', 'confirmation_type', $confirmation_type);

  switch ($confirmation_type) {
    case CONTACT_AJAX_LOAD_FROM_URI:
      $contact_form->setThirdPartySetting('contact_ajax', 'load_from_uri', $form_state->getValue('contact_ajax_load_from_uri'));
      break;
    case CONTACT_AJAX_LOAD_FROM_MESSAGE:
      $contact_form->setThirdPartySetting('contact_ajax', 'load_from_message', $form_state->getValue('contact_ajax_load_from_message'));
      break;
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for contact_form_form().
 */
function contact_ajax_form_contact_message_form_alter(&$form, &$form_state, $form_id) {
  /** @var \Drupal\Core\Entity\ContentEntityForm $form_object */
  $form_object = $form_state->getFormObject();
  /* @var \Drupal\contact\MessageInterface $contact_message */
  $contact_message = $form_object->getEntity();

  $contact_form = ContactForm::load($contact_message->bundle());

  /** @var \Drupal\Core\Entity\Display\EntityFormDisplayInterface $form_mode */
  if ($form_object instanceof MessageForm) {

    $ajax_enabled = $contact_form->getThirdPartySetting('contact_ajax', 'enabled', FALSE);
    $prefix_id = $contact_form->getThirdPartySetting('contact_ajax', 'prefix_id');
    $element_id = $prefix_id ? $prefix_id : CONTACT_AJAX_PREFIX . $form_id;

    if ($ajax_enabled) {

      $form['#prefix'] = '<div id="' . $element_id . '">';
      $form['#suffix'] = '</div>';

      // adjust the form to use ajax submit
      $form['actions']['submit']['#ajax'] = array(
          'callback' => 'contact_ajax_contact_site_form_ajax_callback',
          'wrapper' => $element_id,
          'effect' => 'fade',
      );
    }
  }
}

/**
 * Ajax callback for contact form.
 * @param type $form
 * @param type $form_state
 * @return type
 */
function contact_ajax_contact_site_form_ajax_callback($form, FormStateInterface &$form_state) {

  /** @var \Drupal\Core\Entity\ContentEntityForm $form_object */
  $form_object = $form_state->getFormObject();
  /* @var \Drupal\contact\MessageInterface $contact_message */
  $contact_message = $form_object->getEntity();
  $contact_form = ContactForm::load($contact_message->bundle());
  $confirmation_type = $contact_form->getThirdPartySetting('contact_ajax', 'confirmation_type', FALSE);
  $prefix_id = $contact_form->getThirdPartySetting('contact_ajax', 'prefix_id', FALSE);
  $element_id = $prefix_id ? $prefix_id : CONTACT_AJAX_PREFIX . $form_object->getFormId();

  $messages = StatusMessages::renderMessages(NULL); // Used to display results of drupal_set_message() calls.

  // Create AJAX Response object.
  $response = new AjaxResponse();

  $output = array();

  if (!$form_state->getErrors() && $confirmation_type != CONTACT_AJAX_LOAD_FORM) {
    switch ($confirmation_type) {
      case CONTACT_AJAX_LOAD_FROM_URI:
        // load_from_uri is configured, so load the node content.
        $node_id = $contact_form->getThirdPartySetting('contact_ajax', 'load_from_uri', FALSE);
        $node = Node::load($node_id);
        if ($node) {
          $view_builder = \Drupal::entityTypeManager()->getViewBuilder('node');
          $renderarray = $view_builder->view($node, 'full');
          $output['#markup'] = \Drupal::service('renderer')->renderRoot($renderarray);
        }
        break;
      case CONTACT_AJAX_LOAD_FROM_MESSAGE:
        $confirmation_message = $contact_form->getThirdPartySetting('contact_ajax', 'load_from_message', FALSE);
        $output['#markup'] = $confirmation_message ? $confirmation_message['value'] : '';
        break;
     }
  }
  else if ($form_state->getErrors()) {
    $output[] = $messages;
    $output[] = $form;
  }
  else {
    // default reload the page printing the status message
    $output[] = $messages;
  }

  // TODO: would be nice give an option to render again a cleaned contact form

  $prefix = '#' . $element_id;
  $render_here = $contact_form->getThirdPartySetting('contact_ajax', 'render_selector', FALSE);
  $render_selector = $render_here ? $render_here : $prefix;
  if ($render_selector != $prefix) {
    // if a custom selector is configured hide the form in its old position
    $response->addCommand(new ReplaceCommand($prefix, ''));
  }
  $response->addCommand(new HtmlCommand($render_selector, $output));

  return $response;
}

